FROM python:3.10



# Set build-time environment variable lots of todo
ARG ANTHROPIC_SECRETKEY

ARG DJANGO_SECRET_KEY

ARG POSTGRESQL_INTERNAL_HOST
ARG POSTGRESQL_INTERNAL_PORT
ARG POSTGRESQL_INTERNAL_PASSWORD
ARG POSTGRESQL_INTERNAL_USERNAME
ARG POSTGRESQL_INTERNAL_DBNAME

ARG REDIS_INTERNAL_HOST
ARG REDIS_INTERNAL_PASSWORD

ARG OPENAI_ORG_ID
ARG OPENAI_SECRETKEY


# AWS 配置
ARG AWS_EC2_EXTERNAL_HOST
ARG AWS_EC2_INERNAL_HOST
ARG AWS_EC2_SECRET_KEY
ARG AWS_EC2_ACCESS_KEY

# MINIO 配置
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_S3_ENDPOINT_URL

# wecom 配置
ARG WECOM_CORPID
ARG WECOM_RECEIVE_MESSAGE_TOKEN
ARG WECOM_ENCODING_AES_KEY
ARG WECOM_CHAT_BOT_CORPSECRET

# Set environment variables,lots of to do
ENV ANTHROPIC_SECRETKEY $ANTHROPIC_SECRETKEY

ENV DJANGO_SECRET_KEY $DJANGO_SECRET_KEY

ENV POSTGRESQL_INTERNAL_HOST $POSTGRESQL_INTERNAL_HOST
ENV POSTGRESQL_INTERNAL_PORT $POSTGRESQL_INTERNAL_PORT
ENV POSTGRESQL_INTERNAL_PASSWORD $POSTGRESQL_INTERNAL_PASSWORD
ENV POSTGRESQL_INTERNAL_USERNAME $POSTGRESQL_INTERNAL_USERNAME
ENV POSTGRESQL_INTERNAL_DBNAME $POSTGRESQL_INTERNAL_DBNAME

ENV REDIS_INTERNAL_HOST $REDIS_INTERNAL_HOST
ENV REDIS_INTERNAL_PASSWORD $REDIS_INTERNAL_PASSWORD

ENV OPENAI_ORG_ID $OPENAI_ORG_ID
ENV OPENAI_SECRETKEY $OPENAI_SECRETKEY



# AWS 配置
ENV AWS_EC2_EXTERNAL_HOST $AWS_EC2_EXTERNAL_HOST
ENV AWS_EC2_INERNAL_HOST $AWS_EC2_INERNAL_HOST
ENV AWS_EC2_SECRET_KEY $AWS_EC2_SECRET_KEY
ENV AWS_EC2_ACCESS_KEY $AWS_EC2_ACCESS_KEY

# minio 配置
ENV AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY $AWS_SECRET_ACCESS_KEY
ENV AWS_S3_ENDPOINT_URL $AWS_S3_ENDPOINT_URL


# we com配置
ENV WECOM_CORPID $WECOM_CORPID
ENV WECOM_RECEIVE_MESSAGE_TOKEN $WECOM_RECEIVE_MESSAGE_TOKEN
ENV WECOM_ENCODING_AES_KEY $WECOM_ENCODING_AES_KEY
ENV WECOM_CHAT_BOT_CORPSECRET $WECOM_CHAT_BOT_CORPSECRET

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1



LABEL version ="0.1"
LABEL maintainer="David zhu"


#### to do list
# 创建一个项目文件
RUN mkdir /wecomproject

# 创建一个 static 静态文件夹，用来存放 python manage.py collectstatic 的目录
RUN mkdir /djangostatic

# 把当前路径下的 django项目 文件夹(比如myobject1)的内容 拷贝到容器 /djangotest 文件夹下
# 注意如果是文件夹的话，这里的必须是相对路径
COPY . /wecomproject

# 进入到容器内工作目录就是 
WORKDIR /wecomproject

# 设置时间为上海时间
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime


# 安装 requirements.txt 模块
RUN python -m pip install --upgrade pip
RUN pip install --upgrade pip setuptools
RUN pip install -r requirements.txt
