# Generated by Django 3.2 on 2024-04-03 20:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOT_LLM_CONFIG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.IntegerField(unique=True, verbose_name='bot企业微信代码')),
                ('agent_name', models.CharField(max_length=255, verbose_name='bot企业微信名')),
                ('llm_model_name', models.CharField(choices=[('OpenAI', (('gpt-3.5-turbo', 'gpt-3.5-turbo'), ('gpt-4-turbo-preview', 'gpt-4-turbo-preview'))), ('Claude', (('claude-3-haiku-20240307', 'claude-3-haiku-20240307'), ('claude-3-sonnet-20240229', 'claude-3-sonnet-20240229'), ('claude-3-opus-20240229', 'claude-3-opus-20240229')))], default='gpt-3.5-turbo', max_length=255, verbose_name='LLM Model Name')),
                ('system_prompt', models.TextField(default='you are a helpful ai', verbose_name='LLM System Prompt')),
                ('user_prompt', models.TextField(blank=True, null=True, verbose_name='LLM User Prompt')),
                ('temperature', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.0'))], verbose_name='LLM Temperature')),
                ('max_token_response', models.IntegerField(default=5000, verbose_name='LLM Max Token Return')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
            ],
            options={
                'verbose_name': '机器人配置',
                'verbose_name_plural': '机器人配置',
            },
        ),
        migrations.CreateModel(
            name='GENERALBLACKBOX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('corp_id', models.CharField(max_length=255, verbose_name='')),
                ('event', models.CharField(max_length=255, verbose_name='事件')),
                ('messages', models.JSONField(verbose_name='对话内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apimessage.bot_llm_config', to_field='agent_id')),
            ],
            options={
                'verbose_name': 'General Blackbox',
                'verbose_name_plural': 'General Blackbox',
            },
        ),
    ]
